image: alpine/edge
packages:
    - git
    - scdoc
    - zig
environment:
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
sources:
    - https://git.sr.ht/~gpanders/ztags
triggers:
    - action: email
      condition: failure
      to: Gregory Anders <greg@gpanders.com>
tasks:
    - test: |
        cd ztags
        zig build test
    - docs: |
        # Make sure there are no errors in the man page source
        scdoc < ztags/ztags.1.scd >/dev/null
