image: alpine/edge
packages:
    - git
secrets:
    - 78f39fb6-1185-492f-9c21-f755e10b5e5d # ssh key for mirroring
environment:
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
    - mirror: |
        # Don't run on GitHub PRs
        if [ "$BUILD_REASON" = 'github-pr' ]; then
            exit
        fi

        git clone --mirror https://git.sr.ht/~gpanders/ztags ztags.git
        cd ztags.git
        git push --force --mirror git@github.com:gpanders/ztags
        cd ..
        rm -rf ztags.git
