name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.zig'
      - '.github/workflows/CI.yml'
  push:
    branches:
      - main
    paths:
      - '**.zig'
      - '.github/workflows/CI.yml'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.10.0, master]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}
      - name: fmt
        run: |
          make fmt
      - name: test
        run: |
          make test
